export const songs = {
    "OSFTGH": [
        "Ride For Vengeance",
        "The Dragons' Flight Across The Waves",
        "Without Fear",
        "Victorious March",
        "Friends Of The Suncross",
        "Abandoned",
        "Amon Amarth",
        "Once Sent From The Golden Hall",
        "Siegreicher Marsch (Victorious March - Bonus Track)"
    ],
    "The_Avenger": [
        "Bleed For Ancient Gods",
        "The Last With Pagan Blood",
        "North Sea Storm",
        "Avenger",
        "God, His Son And Holy Whore",
        "Metalwrath",
        "Legend Of A Banished Man",
        "Thor Arise (Bonus Track)"
    ],
    "The_Crusher": [
        "Bastards Of A Lying Breed",
        "Masters Of War",
        "The Sound Of Eight Hooves",
        "Risen From The Sea",
        "As Long As The Raven Flies",
        "A Fury Divine",
        "Annihilation Of Hammerfest",
        "Fall Through Ginnungagap",
        "Releasing Surtur's Fire",
        "Eyes Of Horror (Bonus Track)"
    ],
    "Versus_The_World": [
        "Death in Fire",
        "For the Stabwounds in Our Backs",
        "Where Silent Gods Stand Guard",
        "Versus the World",
        "Across the Rainbow Bridge",
        "Down the Slopes of Death",
        "Thousand Years of Oppression",
        "Bloodshed",
        "...And Soon the World Will Cease to Be"
    ],
    "Fate_Of_Norns": [
        "An Ancient Sign Of Coming Storm",
        "Where Death Seems To Dwell",
        "Fate Of Norns",
        "The Pursuit Of Vikings",
        "Valkyries Ride",
        "The Beheading Of A King",
        "Arson",
        "Once Sealed In Blood"
    ],
    "With_Oden": [
        "Valhall Awaits Me",
        "Runes To My Memory",
        "Asator",
        "Hermod's Ride To Hel - Loke's Treachery Part 1",
        "Gods Of War Arise",
        "With Oden On Our Side",
        "Cry Of The Black Birds",
        "Under The Northern Star",
        "Prediction Of Warfare"
    ],
    "TotTG": [
        "Twilight Of The Thunder God",
        "Free Will Sacrifice",
        "Guardians Of Asgaard",
        "Where Is Your God?",
        "Varyags Of Miklagaard",
        "Tattered Banners And Bloody Flags",
        "No Fear For The Setting Sun",
        "The Hero",
        "Live For The Kill",
        "Embrace The Endless Ocean"
    ],
    "Surtur_Rising": [
        "War of the Gods",
        "Tock's Taunt - Loke's Treachery Part 2",
        "Destroyer of the Universe",
        "Slaves of Fear",
        "Live Without Regrets",
        "The Last Stand of Frej",
        "For Victory or Death",
        "Wrath of the Norsemen",
        "A Beast Am I",
        "Doom Over Dead Man",
        "Aerials (SOTD Cover)"
    ],
    "Deceiver_of_the_Gods": [
        "Deceiver of the Gods",
        "As Loke Falls",
        "Father of the Wolf",
        "Shape Shifter",
        "Under Siege",
        "Blood Eagle",
        "We Shall Destroy",
        "Hel",
        "Coming of the Tide",
        "Warriors of the North"
    ],
    "Jomsviking": [
        "First Kill",
        "Wanderer",
        "On a Sea of Blood",
        "One Against All",
        "Raise Your Horns",
        "The Way of Vikings",
        "At Dawn's First Light",
        "One Thousand Burning Arrows",
        "Vengeance Is My Name",
        "A Dream That Cannot Be (ft. Doro Pesch)",
        "Back on Northern Shores"
    ],
    "Berserker": [
        "Fafner's Gold",
        "Crack the Sky",
        "Mjolner, Hammer of Thor",
        "Shield Wall",
        "Valkyria",
        "Raven's Flight",
        "Ironside",
        "The Berserker at Stamford Bridge",
        "When Once Again We Can Set Our Sails",
        "Skoll and Hati",
        "Wings of Eagles",
        "Into the Dark"
    ]
}